language: python
sudo: false

python:
- '2.7'
- '3.6'

install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
- make test
